In [1]:
import pandas as pd 
import folium
import geopandas

In [2]:
path = f"C:/Users/34639/Desktop/migue/geojson/emiss.geojson"

In [3]:
import geopandas

gdf = geopandas.GeoDataFrame.from_file(path)
gdf

,N_VERTEXS,LONG_ARC,LONG_ARCE,NODE_INI,NODE_FI,ID_USUARI,COD_SIST,NOM,DIAM_SEC,MATER,LONGIT,SITU_ACT,PROF,CATEGORIA,geometry
0,2,300.671,223.330813,3421,3422,1074,ECL,"POBLE, EL",0.0,,0.0,S,0.0,S,"LINESTRING (348870.315 5151240.018, 348877.266..."
1,2,3603.516,2706.865879,3713,3724,501,BSS,EMISSARI(EDAR),2100.0,H,2900.0,S,50.0,P,"LINESTRING (247556.376 5044851.609, 250386.468..."
2,2,3543.289,2661.666429,3713,3725,2,BSS,EMISSARI(FANG),400.0,G,3850.0,J,55.0,F,"LINESTRING (247556.376 5044851.609, 250035.580..."
3,2,1229.790,920.725444,3800,3801,664,PIM,DOCTOR BERTOMEU,355.0,,600.0,S,7.0,E,"LINESTRING (300098.638 5076245.511, 300544.598..."
4,2,2531.915,1877.523221,359,370,174,EPB,EMPURIABRAVA,800.0,A,600.0,P,0.0,P,"LINESTRING (347766.495 5167687.187, 350077.004..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,2,1560.292,1178.299214,4818,4819,104,VLC,MAR I PINS,200.0,G,1292.0,S,37.3,P,"LINESTRING (130506.743 4992801.850, 131658.716..."
132,2,2284.694,1724.969603,4824,4825,81,VLC,PLAÇA CATALUNYA,600.0,B,1200.0,S,19.0,E,"LINESTRING (126976.044 4995495.375, 126155.102..."
133,2,2107.425,1591.583975,4826,4827,102,VLC,CALA CRANCS,250.0,G,1660.0,S,20.0,P,"LINESTRING (130051.304 4992651.455, 129339.697..."
134,2,1211.320,916.434646,4836,4837,1215,ZZZ,Almadrava,315.0,G,975.0,S,0.0,P,"LINESTRING (95272.328 4974750.111, 96399.430 4..."
135,6,296.442,224.444060,15524,18347,12735,AMM,,0.0,,0.0,S,0.0,S,"LINESTRING (89637.196 4967366.860, 89618.818 4..."

In [4]:
import pandas as pd
from simpledbf import Dbf5

PyTables is not installed. No support for HDF output.

In [5]:
path_dbf = f"C:/Users/34639/Desktop/migue/MCARTO/EMISSAR/Emissar_ETRS89A.dbf"

In [6]:
 dbf = Dbf5(path_dbf)

In [7]:
 dbf = Dbf5(path_dbf, codec='latin')

In [8]:
dbf

In [9]:
df = dbf.to_dataframe()

In [10]:
df

,ID_GRAFIC,N_VERTEXS,LONG_ARC,LONG_ARCE,NODE_INI,NODE_FI,ID_USUARI,COD_SIST,NOM,DIAM_SEC,MATER,LONGIT,SITU_ACT,PROF,CATEGORIA
0,0,2,300.671,223.330813,3421,3422,1074,ECL,"POBLE, EL",0.0,NaN,0.0,S,0.0,S
1,1,2,3603.516,2706.865879,3713,3724,501,BSS,EMISSARI(EDAR),2100.0,H,2900.0,S,50.0,P
2,2,2,3543.289,2661.666429,3713,3725,2,BSS,EMISSARI(FANG),400.0,G,3850.0,J,55.0,F
3,3,2,1229.790,920.725444,3800,3801,664,PIM,DOCTOR BERTOMEU,355.0,NaN,600.0,S,7.0,E
4,4,2,2531.915,1877.523221,359,370,174,EPB,EMPURIABRAVA,800.0,A,600.0,P,0.0,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,131,2,1560.292,1178.299214,4818,4819,104,VLC,MAR I PINS,200.0,G,1292.0,S,37.3,P
132,132,2,2284.694,1724.969603,4824,4825,81,VLC,PLAÇA CATALUNYA,600.0,B,1200.0,S,19.0,E
133,133,2,2107.425,1591.583975,4826,4827,102,VLC,CALA CRANCS,250.0,G,1660.0,S,20.0,P
134,134,2,1211.320,916.434646,4836,4837,1215,ZZZ,Almadrava,315.0,G,975.0,S,0.0,P
135,135,6,296.442,224.444060,15524,18347,12735,AMM,NaN,0.0,NaN,0.0,S,0.0,S

# merge by index

In [11]:
df = df.drop(columns=['ID_GRAFIC', 'N_VERTEXS', 'LONG_ARC', 'NODE_INI', 'NODE_FI', 'ID_USUARI',
                 'COD_SIST', 'NOM','NOM', 'MATER', 'SITU_ACT', 'PROF', 'CATEGORIA' ])
df

       LONG_ARCE  DIAM_SEC  LONGIT
0     223.330813       0.0     0.0
1    2706.865879    2100.0  2900.0
2    2661.666429     400.0  3850.0
3     920.725444     355.0   600.0
4    1877.523221     800.0   600.0
..           ...       ...     ...
131  1178.299214     200.0  1292.0
132  1724.969603     600.0  1200.0
133  1591.583975     250.0  1660.0
134   916.434646     315.0   975.0
135   224.444060       0.0     0.0

[136 rows x 3 columns]

In [15]:
df_merged = gdf.merge(df, how='outer', left_index=True, right_index=True)
df_merged

,N_VERTEXS,LONG_ARC,LONG_ARCE_x,NODE_INI,NODE_FI,ID_USUARI,COD_SIST,NOM,DIAM_SEC_x,MATER,LONGIT_x,SITU_ACT,PROF,CATEGORIA,geometry,LONG_ARCE_y,DIAM_SEC_y,LONGIT_y
0,2,300.671,223.330813,3421,3422,1074,ECL,"POBLE, EL",0.0,,0.0,S,0.0,S,"LINESTRING (348870.315 5151240.018, 348877.266...",223.330813,0.0,0.0
1,2,3603.516,2706.865879,3713,3724,501,BSS,EMISSARI(EDAR),2100.0,H,2900.0,S,50.0,P,"LINESTRING (247556.376 5044851.609, 250386.468...",2706.865879,2100.0,2900.0
2,2,3543.289,2661.666429,3713,3725,2,BSS,EMISSARI(FANG),400.0,G,3850.0,J,55.0,F,"LINESTRING (247556.376 5044851.609, 250035.580...",2661.666429,400.0,3850.0
3,2,1229.790,920.725444,3800,3801,664,PIM,DOCTOR BERTOMEU,355.0,,600.0,S,7.0,E,"LINESTRING (300098.638 5076245.511, 300544.598...",920.725444,355.0,600.0
4,2,2531.915,1877.523221,359,370,174,EPB,EMPURIABRAVA,800.0,A,600.0,P,0.0,P,"LINESTRING (347766.495 5167687.187, 350077.004...",1877.523221,800.0,600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,2,1560.292,1178.299214,4818,4819,104,VLC,MAR I PINS,200.0,G,1292.0,S,37.3,P,"LINESTRING (130506.743 4992801.850, 131658.716...",1178.299214,200.0,1292.0
132,2,2284.694,1724.969603,4824,4825,81,VLC,PLAÇA CATALUNYA,600.0,B,1200.0,S,19.0,E,"LINESTRING (126976.044 4995495.375, 126155.102...",1724.969603,600.0,1200.0
133,2,2107.425,1591.583975,4826,4827,102,VLC,CALA CRANCS,250.0,G,1660.0,S,20.0,P,"LINESTRING (130051.304 4992651.455, 129339.697...",1591.583975,250.0,1660.0
134,2,1211.320,916.434646,4836,4837,1215,ZZZ,Almadrava,315.0,G,975.0,S,0.0,P,"LINESTRING (95272.328 4974750.111, 96399.430 4...",916.434646,315.0,975.0
135,6,296.442,224.444060,15524,18347,12735,AMM,,0.0,,0.0,S,0.0,S,"LINESTRING (89637.196 4967366.860, 89618.818 4...",224.444060,0.0,0.0

In [16]:
df_merged.to_file("C:/Users/34639/Desktop/migue/shpf/emiss.shp")

C:\Users\34639\AppData\Local\Temp/ipykernel_28536/4206835393.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  df_merged.to_file("C:/Users/34639/Desktop/migue/shpf/emiss.shp")

In [18]:
gdf = geopandas.GeoDataFrame.from_file("C:/Users/34639/Desktop/migue/shpf/emiss.shp")
gdf

,N_VERTEXS,LONG_ARC,LONG_ARCE_,NODE_INI,NODE_FI,ID_USUARI,COD_SIST,NOM,DIAM_SEC_x,MATER,LONGIT_x,SITU_ACT,PROF,CATEGORIA,LONG_ARC_1,DIAM_SEC_y,LONGIT_y,geometry
0,2,300.671,223.330813,3421,3422,1074,ECL,"POBLE, EL",0.0,None,0.0,S,0.0,S,223.330813,0.0,0.0,"LINESTRING (348870.315 5151240.018, 348877.266..."
1,2,3603.516,2706.865879,3713,3724,501,BSS,EMISSARI(EDAR),2100.0,H,2900.0,S,50.0,P,2706.865879,2100.0,2900.0,"LINESTRING (247556.376 5044851.609, 250386.468..."
2,2,3543.289,2661.666429,3713,3725,2,BSS,EMISSARI(FANG),400.0,G,3850.0,J,55.0,F,2661.666429,400.0,3850.0,"LINESTRING (247556.376 5044851.609, 250035.580..."
3,2,1229.790,920.725444,3800,3801,664,PIM,DOCTOR BERTOMEU,355.0,None,600.0,S,7.0,E,920.725444,355.0,600.0,"LINESTRING (300098.638 5076245.511, 300544.598..."
4,2,2531.915,1877.523221,359,370,174,EPB,EMPURIABRAVA,800.0,A,600.0,P,0.0,P,1877.523221,800.0,600.0,"LINESTRING (347766.495 5167687.187, 350077.004..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,2,1560.292,1178.299214,4818,4819,104,VLC,MAR I PINS,200.0,G,1292.0,S,37.3,P,1178.299214,200.0,1292.0,"LINESTRING (130506.743 4992801.850, 131658.716..."
132,2,2284.694,1724.969603,4824,4825,81,VLC,PLAÇA CATALUNYA,600.0,B,1200.0,S,19.0,E,1724.969603,600.0,1200.0,"LINESTRING (126976.044 4995495.375, 126155.102..."
133,2,2107.425,1591.583975,4826,4827,102,VLC,CALA CRANCS,250.0,G,1660.0,S,20.0,P,1591.583975,250.0,1660.0,"LINESTRING (130051.304 4992651.455, 129339.697..."
134,2,1211.320,916.434646,4836,4837,1215,ZZZ,Almadrava,315.0,G,975.0,S,0.0,P,916.434646,315.0,975.0,"LINESTRING (95272.328 4974750.111, 96399.430 4..."
135,6,296.442,224.444060,15524,18347,12735,AMM,None,0.0,None,0.0,S,0.0,S,224.444060,0.0,0.0,"LINESTRING (89637.196 4967366.860, 89618.818 4..."